---
editor_options: 
  markdown: 
    wrap: sentence
---

# FINAL PROJECT

**Author:** Dawa Oluya 
**Date:** 2024-02-19

## Overview

This repository contains data and code for analyzing the learning attitudes and perceptions of second-year dental students in Korea participating in a clinical periodontology course delivered via YouTube in a flipped classroom setting.
The analysis aims to provide insights into the effectiveness and acceptability of online learning methods in dental education.


## Repository Contents

-   **Data**: The raw data is stored in an Excel file named `raw.xlsx` in the `raw_data` directory.
-   **Code**: The R code for data cleaning, analysis, and visualization is provided in the `code/project_code.Rmd` file.
-   **Output**: The output directory contains the generated summary table (`watched_video.rds`) and figure (`device_frequency.png`).

- **makefile** :for how to make report


## How to Generate the Final Report

To generate the final report: 1.
Set the working directory to the directory containing the R Markdown file: `here::i_am("code/project_code.Rmd")`.
2.
Read the Excel file into R as a data frame and clean the dataset variable names.
3.
Create a summary table of descriptive statistics using the `gtsummary` package.
4. Save the summary table as an RDS file.
5. Count the frequency of each device used by gender and create a bar plot using `ggplot2`.
6. Save the plot as a PNG file.

## Contents of the Report

The report includes: - Descriptive statistics of variables such as gender, location, and whether the video was watched before class.
- A summary table displaying descriptive statistics and p-values organized by the "Watch Before Class" variable.
- A bar plot illustrating the frequency of devices used by gender, facilitating comparison of device usage patterns.

The code for creating the required table is located in the section titled "Creating Summary Table," and the code for generating the figure is located in the section titled "Creating Bar Plot."

## Additional Notes

-   The code provided assumes that necessary R packages (`dplyr`, `ggplot2`, `janitor`, `gtsummary`) are installed.
-   Ensure that the working directory is properly set before running the code.
-   Adjust file paths as needed based on the directory structure.
-   For any questions or issues, feel free to contact the author.
